---
- name: Setup npm to zabbix whatsapp integration
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    - name: Create directory for storage npm files
      file:
        name: "{{ dest_nodes }}"
        state: directory

    - name: Npm configure
      shell: "{{ item }}"
      loop: "{{ npm }}"
      ignore_errors: True
      args:
        chdir: "{{ dest_nodes }}"

    - name: Copy fixed file "{{ src_file }}"
      copy:
        src: "files/{{ src_file }}"
        dest: "{{ dest_file }}"
        backup: yes

    - name: Copy alert script files
      copy:
        src: "files/{{ src_scripts }}"
        dest: "{{ dest_scripts }}"
        backup: no
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    - name: Copy node files
      copy:
        src: "files/{{ item }}"
        dest: "{{ dest_nodes }}"
        backup: no
      loop: "{{ node_files }}"
