---
- name: Include distribution specific vars - "{{ ansible_os_family }}"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  ignore_errors: true

- name: Running tasks for distribution - "{{ ansible_os_family }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  ignore_errors: true
